name: Checks

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 'Use NodeJS 16'
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'

      - name: 'Install dependencies'
        run: | # Install and link dependencies
          yarn set version 3.4.1
          yarn install

      - name: 'Build'
        run: |
          yarn build
